// Copyright 2023-2024 The Regents of the University of California
// Copyright 2024 Cornell University
// released under BSD 3-Clause License
// author: Kevin Laeufer <laeufer@cornell.edu>

use patronus::btor2;
use patronus::expr::*;
use patronus::system::transform::{replace_anonymous_inputs_with_zero, simplify_expressions};

const COUNT_2: &str = r#"
1 sort bitvec 3
2 zero 1
3 state 1
4 init 1 3 2
5 one 1
6 add 1 3 5
7 next 1 3 6
8 ones 1
9 sort bitvec 1
10 eq 9 3 8
11 bad 10
"#;

const DUPLICATE_LABEL_TARGETS: &str = r#"
1 sort bitvec 1
2 zero 1
3 constraint 2
4 constraint 2
5 bad 2
6 bad 2
"#;

#[test]
fn parse_count2() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, COUNT_2, Some("count2")).unwrap();
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn serialize_count2() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, COUNT_2, Some("count2")).unwrap();
    insta::assert_snapshot!(skip_first_line(&btor2::serialize_to_str(&ctx, &sys)));
}

#[test]
fn serialize_duplicate_bad_and_constraint_targets() {
    let mut ctx1 = Context::default();
    let sys1 = btor2::parse_str(&mut ctx1, DUPLICATE_LABEL_TARGETS, Some("duplicate")).unwrap();
    let text1 = btor2::serialize_to_str(&ctx1, &sys1);

    let mut ctx2 = Context::default();
    let sys2 = btor2::parse_str(&mut ctx2, &text1, Some("duplicate")).unwrap();
    let text2 = btor2::serialize_to_str(&ctx2, &sys2);

    assert_eq!(skip_first_line(&text1), skip_first_line(&text2));
}

const PASS_THROUGH: &str = r#"
1 sort bitvec 1
2 input 1 i
3 output 2 o
"#;

#[test]
fn serialize_pass_through() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, PASS_THROUGH, Some("pass")).unwrap();
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn parse_quiz1() {
    let (ctx, sys) = btor2::parse_file("../inputs/chiseltest/Quiz1.btor").unwrap();
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn serialize_quiz1() {
    let (ctx, sys) = btor2::parse_file("../inputs/chiseltest/Quiz1.btor").unwrap();
    insta::assert_snapshot!(skip_first_line(&btor2::serialize_to_str(&ctx, &sys)));
}

#[test]
fn parse_instrumented_decoder() {
    let (ctx, sys) =
        btor2::parse_file("../inputs/repair/decoder_3_to_8.instrumented.btor").unwrap();
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn parse_sdram() {
    let (mut ctx, mut sys) =
        btor2::parse_file("../inputs/repair/sdram_controller.original.btor").unwrap();
    replace_anonymous_inputs_with_zero(&mut ctx, &mut sys);
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn parse_sdram_and_remove_anonymous_inputs() {
    let (mut ctx, mut sys) =
        btor2::parse_file("../inputs/repair/sdram_controller.original.btor").unwrap();
    replace_anonymous_inputs_with_zero(&mut ctx, &mut sys);
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn parse_sdram_and_simplify_expressions() {
    let (mut ctx, mut sys) =
        btor2::parse_file("../inputs/repair/sdram_controller.original.btor").unwrap();
    replace_anonymous_inputs_with_zero(&mut ctx, &mut sys);
    simplify_expressions(&mut ctx, &mut sys);
    // println!("{}", sys.serialize_to_str(&ctx));
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

/// Regression test for a bug that would prevent "_input_0" from being listed as a system input.
/// The reason was that we did not handle inputs that are also outputs well.
#[test]
fn parse_sha3_keccak_and_check_that_all_anonymous_inputs_are_there() {
    let (ctx, sys) =
        btor2::parse_file("../inputs/repair/sha3_keccak.w2.replace_variables.btor").unwrap();
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

/// Regression test to make sure that when an input that is also an output is set to zero,
/// it is maintained.
#[test]
fn parse_sha3_keccak_and_replace_anonymous_inputs() {
    let (mut ctx, mut sys) =
        btor2::parse_file("../inputs/repair/sha3_keccak.w2.replace_variables.btor").unwrap();
    replace_anonymous_inputs_with_zero(&mut ctx, &mut sys);
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

fn skip_first_line(value: &str) -> &str {
    match value.char_indices().find(|(_, c)| *c == '\n') {
        None => "",
        Some((char_ii, _)) => &value[(char_ii + 1)..],
    }
}

#[test]
#[ignore] // TODO: this test was randomly failing on the CI, but passing locally.
fn parse_lakeroad_dsp48_e2() {
    let (mut ctx, mut sys) = btor2::parse_file("../inputs/lakeroad/DSP48E2.btor").unwrap();
    replace_anonymous_inputs_with_zero(&mut ctx, &mut sys);
    simplify_expressions(&mut ctx, &mut sys);
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

const INVERTER: &str = r#"
; BTOR description generated by Yosys 0.51 (git sha1 c4b5190229616f7ebf8197f43990b4429de3e420, clang++ 16.0.0 -fPIC -O3) for module inverter_d0.
1 sort bitvec 32
2 input 1 a ; /Users/nikilshyamsunder/capra/protocols/examples/inverters/inverter_d0.v:2.19-2.20
3 not 1 2 $not$/Users/nikilshyamsunder/capra/protocols/examples/inverters/inverter_d0.v:6$1 ; /Users/nikilshyamsunder/capra/protocols/examples/inverters/inverter_d0.v:6.16-6.18
4 output 3 s ; /Users/nikilshyamsunder/capra/protocols/examples/inverters/inverter_d0.v:3.19-3.20
; end of yosys output
"#;

#[test]
fn serialize_inverter() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, INVERTER, Some("inverter_d0")).unwrap();
    // check to make sure the output and input names are correct
    let inputs: Vec<_> = sys
        .inputs
        .iter()
        .map(|i| ctx.get_symbol_name(*i).unwrap().to_string())
        .collect();
    let outputs: Vec<_> = sys
        .outputs
        .iter()
        .map(|o| ctx[o.name].to_string())
        .collect();
    assert_eq!(inputs, ["a"]);
    assert_eq!(outputs, ["s"]);
    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

#[test]
fn parse_llsdspi_bug_c1_instrumented() {
    let (mut ctx, mut sys) =
        btor2::parse_file("../inputs/repair/llsdspi_bug_c1.instrumented.btor").unwrap();
    replace_anonymous_inputs_with_zero(&mut ctx, &mut sys);
    simplify_expressions(&mut ctx, &mut sys);
    println!("{}", sys.serialize_to_str(&ctx));
}

// Small circuit with negated line IDs
const NEG_LINES: &str = r"
        1 sort bitvec 1
        2 zero 1
        3 state 1 first
        4 state 1 sec
        5 init 1 3 2
        6 init 1 4 2
        7 and 1 -3 4
        8 output 7 out
        ";

#[test]
fn parse_neg_nodes() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, NEG_LINES, Some("neg_lines")).unwrap();

    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

/// Small circuit with large line numbers
const LARGE_LINES: &str = r"
        1 sort bitvec 1
        2 zero 1
        3 state 1 first
        4 state 1 sec
        5 init 1 3 2
        6 init 1 4 2
        4294967295 and 1 -3 4
        8 output 4294967295 out
        ";

#[test]
fn parse_large_line() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, LARGE_LINES, Some("large_lines")).unwrap();

    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

/// More complex circuit with negated line IDs
const COMPLEX_NEG_LINES: &str = r"
        1 sort bitvec 1
        2 zero 1
        3 ones 1
        4 state 1 first
        5 state 1 sec
        6 state 1 third
        7 init 1 4 3
        8 init 1 5 2
        9 init 1 6 3
        10 and 1 4 -6
        11 or 1 -10 6
        12 xor 1 4 -11
        13 input 1 act
        14 implies 1 13 12
        15 output 14 out
        ";

#[test]
fn complex_parse_neg_nodes() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, COMPLEX_NEG_LINES, Some("complex_neg_lines")).unwrap();

    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

/// Circuit with non-Boolean (i.e. not length-1) bitvectors
const NON_BOOL_NEG_LINES: &str = r"
       1 sort bitvec 3
       2 zero 1
       3 state 1 first
       4 state 1 sec
       5 init 1 3 2
       6 init 1 4 2
       7 and 1 -3 4
       8 output 7 out
       ";

#[test]
fn non_bool_parse_neg_nodes() {
    let mut ctx = Context::default();
    let sys = btor2::parse_str(&mut ctx, NON_BOOL_NEG_LINES, Some("non_bool_neg_lines")).unwrap();

    insta::assert_snapshot!(sys.serialize_to_str(&ctx));
}

/// Circuit with negated type references
const NEG_LINE_TYPE: &str = r"
       1 sort bitvec 1
       2 zero 1
       3 state 1 first
       4 state -1 sec
       5 init 1 3 2
       6 init 1 4 2
       7 and 1 -3 4
       8 output 7 out
       ";

/// Circuit with negated line numbers
const NEG_LINE_NUM: &str = r"
       1 sort bitvec 1
       2 zero 1
       -3 state 1 first
       4 state 1 sec
       5 init 1 3 2
       6 init 1 4 2
       7 and 1 -3 4
       8 output 7 out
       ";

/// Circuit with overflowed line numbers
const OVERFLOW_LINE_NUM: &str = r"
       1 sort bitvec 1
       2 zero 1
       -3 state 1 first
       4 state 1 sec
       5 init 1 3 2
       6 init 1 4 2
       4294967296 and 1 -3 4
       8 output 4294967296 out
       ";

/// Circuit with overflowed line numbers (negative wrap-around)
const OVERFLOW_LINE_NUM_NEG: &str = r"
       1 sort bitvec 1
       2 zero 1
       -3 state 1 first
       4 state 1 sec
       5 init 1 3 2
       6 init 1 4 2
       -9223372036854775808 and 1 -3 4
       8 output -9223372036854775808 out
       ";

#[test]
fn parse_neg_nodes_errors() {
    for test in [
        NEG_LINE_TYPE,
        NEG_LINE_NUM,
        OVERFLOW_LINE_NUM,
        OVERFLOW_LINE_NUM_NEG,
    ] {
        let mut ctx = Context::default();
        assert!(btor2::parse_str(&mut ctx, test, Some("error_test")).is_none());
    }
}

/// Serialize → parse → serialize, then require the two serializations match.
/// This is the strongest check we can make without comparing IR directly: any
/// information the serializer drops or mangles will show up as a text diff on
/// the second pass.
fn check_roundtrip(path: &str) {
    let (ctx1, sys1) = btor2::parse_file(path).unwrap_or_else(|| panic!("failed to parse {path}"));
    let text1 = btor2::serialize_to_str(&ctx1, &sys1);

    let mut ctx2 = Context::default();
    let sys2 = btor2::parse_str(&mut ctx2, &text1, Some(&sys1.name)).unwrap_or_else(|| {
        panic!("failed to re-parse serializer output for {path}. Output was:\n{text1}")
    });
    let text2 = btor2::serialize_to_str(&ctx2, &sys2);

    assert_eq!(
        skip_first_line(&text1),
        skip_first_line(&text2),
        "btor2 serialization is not a fixed point for {path}"
    );
}

#[test]
fn roundtrip_unittest_delay() {
    check_roundtrip("../inputs/unittest/delay.btor");
}

#[test]
fn roundtrip_unittest_swap() {
    check_roundtrip("../inputs/unittest/swap.btor");
}

#[test]
fn roundtrip_quiz1() {
    check_roundtrip("../inputs/chiseltest/Quiz1.btor");
}

#[test]
fn roundtrip_quiz1_unsat() {
    check_roundtrip("../inputs/chiseltest/Quiz1.unsat.btor");
}

#[test]
fn roundtrip_quiz2_sat() {
    check_roundtrip("../inputs/chiseltest/Quiz2.sat.btor");
}

#[test]
fn roundtrip_quiz2_unsat() {
    check_roundtrip("../inputs/chiseltest/Quiz2.unsat.btor");
}

#[test]
fn roundtrip_const_array_example() {
    check_roundtrip("../inputs/chiseltest/const_array_example.btor");
}

#[test]
fn roundtrip_instrumented_decoder() {
    check_roundtrip("../inputs/repair/decoder_3_to_8.instrumented.btor");
}

#[test]
fn roundtrip_sdram_controller() {
    check_roundtrip("../inputs/repair/sdram_controller.original.btor");
}

#[test]
fn roundtrip_mux_4_1() {
    check_roundtrip("../inputs/repair/mux_4_1.original.btor");
}

#[test]
fn roundtrip_axi_lite_xlnx() {
    check_roundtrip("../inputs/repair/axi-lite-xlnx.original.btor");
}

#[test]
fn roundtrip_axis_async_fifo_wrapper() {
    check_roundtrip("../inputs/repair/axis-async-fifo-wrapper.original.btor");
}

#[test]
fn roundtrip_i2c_m_replace_literals() {
    check_roundtrip("../inputs/repair/i2c_m.original.replace_literals.btor");
}

#[test]
fn roundtrip_llsdspi_bug_c1_instrumented() {
    check_roundtrip("../inputs/repair/llsdspi_bug_c1.instrumented.btor");
}

#[test]
fn roundtrip_sha3_keccak() {
    check_roundtrip("../inputs/repair/sha3_keccak.w2.replace_variables.btor");
}

#[test]
fn roundtrip_lakeroad_dsp48e2() {
    check_roundtrip("../inputs/lakeroad/DSP48E2.btor");
}
