name: Setup Z3

inputs:
  version:
    description: version to install
    required: true
  glibc_version:
    description: glibc version of the release archive
    required: true

runs:
  using: composite
  steps:
    - name: Cache Z3
      id: cache-z3
      uses: actions/cache@v5
      with:
        key: z3-${{ runner.os }}-${{ inputs.version }}-glibc-${{ inputs.glibc_version }}
        path: /tmp/z3
    - name: Download Z3
      shell: sh
      if: ${{ steps.cache-z3.outputs.cache-hit != 'true' }}
      run: |
        mkdir /tmp/z3
        cd /tmp/z3
        wget -q https://github.com/Z3Prover/z3/releases/download/z3-${{ inputs.version }}/z3-${{ inputs.version }}-x64-glibc-${{ inputs.glibc_version }}.zip -O z3.zip
        unzip -q z3.zip
        mv z3-*/* .
    - name: Add Z3 to Path
      shell: sh
      run: echo "/tmp/z3/bin" >> "$GITHUB_PATH"