name: Setup CVC5

inputs:
  version:
    description: version to install
    required: true

runs:
  using: composite
  steps:
    - name: Cache CVC5
      id: cache-cvc5
      uses: actions/cache@v5
      with:
        key: cvc5-${{ runner.os }}-${{ inputs.version }}
        path: /tmp/cvc5
    - name: Download CVC5
      shell: sh
      if: ${{ steps.cache-cvc5.outputs.cache-hit != 'true' }}
      run: |
        mkdir /tmp/cvc5
        cd /tmp/cvc5
        wget -q https://github.com/cvc5/cvc5/releases/download/cvc5-${{ inputs.version }}/cvc5-Linux-x86_64-static-gpl.zip -O cvc5.zip
        unzip -q cvc5.zip
        mv cvc5-*/* .
    - name: Add CVC5 to Path
      shell: sh
      run: echo "/tmp/cvc5/bin" >> "$GITHUB_PATH"